title: .pip Framework Blog
description: Building Agentic Development Systems
url: https://derrybirkett.github.io
baseurl: /pip-blog
remote_theme: patdryburgh/hitchens

# Build settings
markdown: kramdown

# Exclude from build
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - bin
  - docs
  - fragments
  - graph
  - hooks
  - ia
  - method
  - mission
  - patterns
  - resources

# Include
include:
  - _posts

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# SEO
author: .pip Framework
social:
  name: .pip Framework
  links:
    - https://github.com/derrybirkett/pip

# RSS
feed:
  path: feed.xml

# Excerpts
show_excerpts: false
excerpt_length: 0
excerpt_separator: "<!--more-->"

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Permalink structure
permalink: /:year/:month/:day/:title/
